apiVersion: v1
kind: Service
metadata:
  name: financial-nlp-svc
spec:
  selector:
    app: financial-nlp
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
